### PR TITLE
Add erlang 20

### PR DESCRIPTION
**Pull request by goncalotomas**
Ran the following commands before opening this PR:

```bash
rebar get-deps
rebar compile
rebar eunit
rebar ct
rebar release
```

No errors or warnings.

### CODE REVIEW

**Comment by wohali** [comment]
Could you update the `.travis.yml` file in your branch to test 19 and 20? That will let us see that everything is good thru the GH-Travis integration. (Also, please squash your branch.) Thanks!

**Comment by goncalotomas** [comment]
Sorry, I'm having a hard time squashing my branch, I don't know how to do it. I have a feeling that last Merge branch 'master' ruined it, am I right?

How do I do it properly?

**Comment by wohali** [comment]
Ah, ok, that's not good. Remove 20 from the Travis file for now.

Try a `git rebase -i HEAD~4` and squash everything but the first commit.

**Comment by goncalotomas** [comment]
Another option is to add `20.0-rc1` (available on Travis) and then just replace it for `20.0` when it's available. What should we do?

**Comment by wohali** [comment]
Ah, that'll do. Submit with `20.0-rc1` if you please.

**Comment by goncalotomas** [comment]
Can you confirm I squashed the commits correctly?

**Comment by wohali** [comment]
Looks great, I'll merge this now.

Thank you for your contribution to Apache CouchDB! 👯

**Pull request merged**
