### PR TITLE
Build with Erlang 21

### PR DESCRIPTION
**Pull request by nickva**
Issue #1396

### CODE REVIEW

**Comment by nickva** [comment]
Not sure why travis doesn't work but local tests do pass with 21:
```
 make check
rebar compile
==> snappy (compile)
rebar eunit
==> snappy (eunit)
Compiled src/snappy.erl
Compiled test/snappy_tests.erl
======================== EUnit ========================
module 'snappy'
  module 'snappy_tests'
    snappy_tests: compression_test_...ok
    snappy_tests: decompression_test_...ok
    [done in 0.496 s]
  [done in 0.496 s]
=======================================================
  2 tests passed.
```

**Comment by davisp** [comment]
Is it normal for all of the tests to fail?

**Comment by nickva** [comment]
Trying to use rebar3 maybe and it can't build the nif properly?

**Comment by nickva** [comment]
Yap all travis builds fail apparently now. Here is a change to the README file: https://travis-ci.org/apache/couchdb-snappy/builds/395127559?utm_source=github_status&utm_medium=notification

**Comment by davisp** [comment]
+1

**Comment by davisp** [comment]
Tested locally and it works so will ignore it.

**Comment by davisp** [comment]
Oh, except it looks like we have to make them pass for the merge button?

**Comment by davisp** [comment]
Oh, its a permissions thing. Ignore my rambling.

**Comment by nickva** [comment]
Yap, merged it via ASF. Still not sure why build failed. I had tried compiling with rebar3 locally and that worked as well. A different C compiler or libc version... who knows...

**Pull request merged**
