### PR TITLE
Add OTP 23 support

### PR DESCRIPTION
**Pull request by noahshaw11**
Add OTP 23 support

### CODE REVIEW

**Review by nickva — APPROVED** [review]
+1

**Comment by nickva** [comment]
@noahshaw11 I just realized that we shouldn't be using master branch, I just noticed that we updated master branch here.

**Comment by noahshaw11** [comment]
@nickva The goal was to pull the upgrade to OTP 23 changes from main into master to fix the issue with OTP 23 not being supported for snappy in 3.x.

**Comment by nickva** [comment]
Apache CouchDB uses `main` for development. `master` should not be used. In the main repo `rebar.config.script` should point to tagged releases off of the `main` branch.

**Pull request merged**
